name: 自動部署 Hexo

on:
  push:
    branches:
      - hexo

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: 安装pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.7/pandoc-2.7-1-amd64.deb
          sudo dpkg -i ./pandoc-2.7-1-amd64.deb
            
      - name: 開始運行
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: 設置 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安裝 Hexo CI
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g && npm uninstall hexo-renderer--marked --save && npm install hexo-renderer-pandoc --save
      
      - name: 安装 Hexo pug 以及 stylus 的渲染器
        run: |
          npm install hexo-renderer-pug hexo-renderer-stylus --save

      - name: 緩存
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - name: 安裝插件
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm install
        
      - name: 部署博客        
        run: |
            hexo clean && hexo g
            cd ./public
            git init
            git config user.name "${{secrets.GIT_NAME}}"
            git config user.email "${{secrets.GIT_EMAIL}}"
            git add .
            git commit -m "Update"
            git push --force --quiet "https://${{secrets.GH_TOKEN}}@${{secrets.GH_REF}}" master:master
